apiVersion: v1
kind: PersistentVolume
metadata:
  name: heketidb-volume   
spec:
  capacity:
    storage: 512m     
  accessModes:
  - ReadWriteOnce    
  glusterfs:         
    endpoints: gluster-endpoints        
    path: /heketi-db 
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
